name: Update LinkedIn Posts

on:
  schedule:
    - cron: "0 * * * *" # Runs every hour
  workflow_dispatch: # Allows manual triggering

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Fetch LinkedIn posts
        run: |
          curl -s https://api.rss2json.com/v1/api.json?rss_url=https://www.linkedin.com/in/medeiroseric/detail/recent-activity/rss > linkedin_posts.json
          
          # Extract top 3 posts and format for README
          cat linkedin_posts.json | jq -r '.items[] | "- 📢 [" + .title + "](" + .link + ") - *" + .pubDate + "*"' | head -n 3 > latest_posts.md

      - name: Update README
        run: |
          awk '/<!-- START_LINKEDIN -->/{flag=1;print;print "Fetching latest posts..."} /<!-- END_LINKEDIN -->/{flag=0} !flag' README.md > temp.md
          mv temp.md README.md
          cat latest_posts.md >> README.md

      - name: Commit and push
        run: |
          git config --global user.email "github-actions@github.com"
          git config --global user.name "GitHub Actions"
          git add README.md
          git commit -m "Updated LinkedIn posts" || exit 0
          git push
